openapi: 3.1.0
info:
  version: 1.0.0
  title: Water tracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    This is a documentation of water tracker app
tags:
  - name: User
    description: Operations about users.
  - name: Water
    description: Water operations.
servers:
  - url: https://lightningbackend.onrender.com

  - url: http://localhost:3000
    description: Local development server
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/users/register/post.yaml

  /users/login:
    post:
      $ref: ../swagger/paths/users/login/post.yaml

  /users/logout:
    post:
      $ref: ../swagger/paths/users/logout/post.yaml

  /users/update:
    patch:
      $ref: ../swagger/paths/users/update/patch.yaml

  /users/refresh:
    post:
      $ref: ../swagger/paths/users/refresh/post.yaml

  /users/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml

  /water/day:
    post:
      $ref: ../swagger/paths/water/day/post.yaml

  /water/day/{id}:
    patch:
      $ref: ../swagger/paths/water/day/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/day/{id}/delete.yaml

  /water/fullDay:
    get:
      $ref: ../swagger/paths/water/fullDay/get.yaml

  /water/fullMonth:
    get:
      $ref: ../swagger/paths/water/fullMonth/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
